export default {
  locale: 'en',
  messages: {
    siteTitle: 'Valentin Portillo Portfolio',
    addPost: 'Add Post',
    switchLanguage: 'Switch Language',
    twitterMessage: 'We are on Twitter',
    by: 'By',
    deletePost: 'Delete Post',
    createNewPost: 'Create new post',
    authorName: 'Author\'s Name',
    postTitle: 'Post Title',
    postContent: 'Post Content',
    submit: 'Submit',
    comment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	}`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
    	  =0 {does not have <i style='font-style: italic'>any</i> comments}
    	  =1 {has <i style='font-style: italic'>#</i> comment}
    	  other {has <i style='font-style: italic'>#</i> comments}
    	}`,
    nestedDateComment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
      } as of {date}`,
    profileTitle: 'Profile',
    menuAbout: 'Main',
    menuSkills: 'Skills',
    menuResume: 'Resume',
    menuContact: 'Contact',
    menuProjects: 'Projects',
    Me1:'I started my professional career as a Civil Engineer and then I made my life to toggle over Computer Science, totally related with the fact that I always loved logic and technology. While a Civil Engineer I mainly worked doing management since I find organizing, and decision making challenging and very attractive, curious note: I used to automate my work. Nowadays, I\'m doing a Computer Science related Master in order to mix these passions of mine: MSc in Data Science where data should be understood, tendencies bring us to decisions and yet, visualization is crucial for communication, all with the help of algorithms and logic.',
    Me2: 'Before my first Computer Science role, as mentioned before, I used to automate all my activities related to Management, followed by a 2 years plan to get the knowledge of a computer science student, I got to finally work as one, starting with Automation and then, as a Software Engineer in the fields of finances and banking.',
    Me3: 'So, to remark, this path shows, among others, perseverance, autonomy and motivation. Values that I believe are really appreciated, thing that I would rather search if I was going to hire someone.',
    Me4: 'Before concluding, humility a part, I have the skills to do a Software Engineering project start-to-end, the skills for management including the soft skills as leadership and structuring (also in working structures: SCRUM, Waterfall, PMI), the skills for Data Science like communicating, analytics and logic, and the hunger to apply the new hard skills acquired in the MSc.',
    MeConc: 'Finally, I invite you to take a look in my projects, to my "rolling résumé" and if you still don\'t want to contact me (by the end there\'s mail, linkedin ...), maybe you can give me any feedback to improve myself. Anyway, thank you and good recruitment! :)',
    KeyW: 'Key Words',
    KeyWords: 'Data Science, Computer Science, Artificial Intelligence, Business Analysis, Automation, Project Management, Optimization, Entrepreneurship',
    //Soft Skills
    SS1: 'Analytic',
    SS2: 'Commitment',
    SS3: 'Problem Solver',
    SS4: 'Learner',
    SS5: 'Team-Work',
    SS6: 'Add Value',
    SS7: 'Hands On',
    ss11: '& Curious',
    ss12: 'Logic, Reasoning, Dig deeper',
    ss21: 'Deliver Ended Products',
    ss31: 'Find the root',
    ss32: 'Develop a logical step-by-step',
    ss33: 'Deliver a system',
    ss41: 'Self-taught',
    ss42: 'Enthousiastic',
    ss43: 'Ask questions',
    ss51: 'Know How',
    ss52: 'Social',
    ss53: 'Ask & Answer',
    ss61: 'Proposals',
    ss62: 'Business/Product Understanding',
    ss71: 'Try new stuff',
    ss72: 'Eager to Create',
    //hardSkills
    ttLang: 'Languages',
    ttProgLang: 'Programming Languages',
    ttStacks: 'Stacks',
    ttFrameworks: 'Frameworks/Libraries',
    ttOther: 'Other',
    //Resume
    ResHighShool: ' Lycée Franco Mexicain (High School)',
    ResHighShoolSpe: 'Engineering Science Specialization',
    ResUniv: 'Universidad Nacional Autónoma de México - UNAM',
    ResUnivSpe: 'Bachelor of Science in Civil Engineering',
    ResDiploIMEI: 'Intelligent Building Mexican Institute - IMEI',
    ResDiploIMEISpe: 'Speciality - Intelligent & Sustainable Buildings Technology',
    ResStudClubCICM: 'CICM Students Club Memeber',
    ResStageIUNAM: 'Traineeship at a InnovaUNAM (business incubator)',
    ResSolarDec: 'Solar Decathlon Europe 2014',
    ResSolarDecRole: 'Leader, Civil Engineering Responsible',
    ResSolarDecPrices: 'Won 3 prices (1° Engineering, 2° Urbanism, 3° Sustainability)',
    ResThesis: 'Author and Expositor of an article regarding my bachelor thesis (\'Analysis, Design and Construction of the CASA TEAM project\')',
    ResICAF: 'ICA FLUOR',
    ResICAFRole: 'Project Engineer',
    ResICAFDesc: 'Program follow up, alerts, recovery plan, management level reports, forecasts, productivity.',
    ResICAFAchi: 'Follow Up Automation',
    ResJacEng: 'Jacobs Engineering',
    ResJacEngRole: 'Project Scheduler',
    ResJacEngDesc: 'Interactive planning, Master Plan and WBS creation, program follow up, alerts, forecasts, productivity, recovery plan, management level reports, and resources graph.',
    ResJacEngAchi: 'Follow Up Automation',
    ResCitiB: 'Citi Banamex',
    ResCitiBRole: 'Project Manager Jr. / IT Business Analyst',
    ResCitiBDesc: 'Intermediary between business, software developers and specialists. IT BA SDLC deliverables. Data Qty & Project Controls RPA, data analysis and visualization. Requirements and solutions analysis.',
    ResCitiBAchi: 'Follow Up Automation',
    ResDiploTUDelft: 'TUDelft - TPM1x: Creative Problem Solving and Decision Making',
    ResDiploHarv: 'Harvard - CS50: Introduction to Computer Science',
    ResDiploFCCFront: 'FreeCodeCamp - Front End Certification',
    ResDiploSAOpSys: 'Saylor Academy - CS401: Operating Systems',
    ResMutuo: 'Mutuo Financiera',
    ResMutuoRole: 'Software Engineer',
    ResMutuoDesc: 'Internal software development (MVC) and API, RPA for different projects (get/analyze and deduce from data) using Laravel framework mainly and VBA.',
    ResMutuoAchi: 'Projects Follow Up Automation, Scalability, Financial Projects',
    ResDiploSAIntroDB: 'Saylor Academy - CS403: Introduction to Modern Databases',
    ResDiploSAAlgorithm: 'Saylor Academy - CS303: Algorithms',
    ResIMT: 'Institut Mines Télécom - IMT',
    ResIMTP: 'IMT Project',
    ResIMTSpe: 'Master of Science in Data Science',
    ResIMTCours: 'Artificial Intelligence, Languages and Logic, Graphs, Software Engineering, Mathematics {Proba, Stat, Alg}, Signal Processing, Operational Research, Big Data, Data Mining',
    ResIMTP1: 'Project: City Heating Network Optimization using a Genetic Algorithm',
    ResIMTP2: 'Project: Ship Detection using Satellite Images (IA, Statistiques)',
    ResIMTP3: 'Project: Compiler Expr - Pfx type (Lexer, Parser, NLP, Functional Programming)',
    ResIMTP4: 'Project: Infection Simulation and Social Netwoks treatment (Graphes)',
    ResIRH: 'Rent Platform',
    ResIRHRole: 'Side Project',
    ResIRHDesc: 'Develop a Web Application to handle Rents',
    //Form
    Name: 'Name',
    Send: 'Send',
    Email: 'Email',
    Industry: 'Industry',
    Purpose: 'Purpose',
    WriteToMe: 'Write me :)',
    SentMessage: 'Message Sent!! :). Thank you for contacting me, I\'ll respond ASAP. Have a nice day!',
    MessageSentFail: 'Mesage NOT Sent :(, please. try later or contact me directly to my e-mail: valentin.pg@outlook.com. Thanks!',
    WaitForIt: 'Wait for it ...',

    //Time
    January: 'January',
    February: 'February',
    March: 'March',
    June: 'June',
    September: 'September',
    October: 'October',
    December: 'December',
    ToDate: 'To Date',

    //Projects
    project_irent_description: 'Develop a Rent Plataform so that traditional businesses (thinking more in real state managers) can control the properties they manage. From comunication, reports, contracts to payments and data visualization/analysis',

    project_valhalla_status: 'Sorry, "Valhalla" is private, but you can click and access to the public page :)',
    project_valhalla_title: 'Fintech Core Banking System (ERP)',
    project_valhalla_role: 'Software Engineer',
    project_valhalla_context: 'Fintech / RPA',
    project_valhalla_description: 'We wanted to create our own software in order to model every product and financial products as we wanted. So, there you will find a huge related database, clients, products, financial products and all you can imagine to automate and help business ...',
  
    project_datavis_status: 'Click on the links :)',
    project_datavis_title: 'Data Visualization',
    project_datavis_role: 'Student',
    project_datavis_context: 'Data Visualization',
    project_datavis_description: 'Data is one of the most valuable things for business and, one of the most enlightening tools on decision making, so it was a must.',

    project_pm_status: "Sorry, private projects because of sensitive information, but there's a video :)",
    project_pm_title: 'Project Management Tool Dev.',
    project_pm_role: 'Project Manager / Software Engineer',
    project_pm_context: 'Project / Product Management / RPA',
    project_pm_description: 'In order to avoid errors and excel on projects follow up, I created in ICA FLUOR, Jacobs, Citi Banamex, and Mutuo Financiera files like this one for myself as PM or to the PMOffice.',
    
    project_ttt_status: "Click to Play :)",
    project_ttt_title: 'Tic-Tac-Toe Game',
    project_ttt_role: 'Student',
    project_ttt_context: 'Artificial Inteligence Principles',
    project_ttt_description: 'When studing the AI principles, this was a project to preactice and understand better this example.',

    project_cs50final_status: "Click to See :)",
    project_cs50final_title: 'CS50 Final - Final Project',
    project_cs50final_role: 'Student',
    project_cs50final_context: 'Web development',
    project_cs50final_description: 'The final project, I chose to do a coffee management software. If you want to understand its functionaliity, watch the video, click in the title.',
  
    project_cs50p8_status: "Click to See :)",
    project_cs50p8_title: 'CS50 Pset8 - Google Maps & Search',
    project_cs50p8_role: 'Student',
    project_cs50p8_context: 'Web development',
    project_cs50p8_description: 'A project left for the Pset8 during the CS50 course.',

    project_cs50p7_status: "Click to See :)",
    project_cs50p7_title: 'CS50 Pset7 - Stock Exchange',
    project_cs50p7_role: 'Student',
    project_cs50p7_context: 'Web development',
    project_cs50p7_description: ' A project left for the Pset7 during the CS50 course.',

    project_fccback_status: "Click on the links :)",
    project_fccback_title: 'Some Back-End projects',
    project_fccback_role: 'Student',
    project_fccback_context: 'Learning NodeJS mainly and some frameworks',
    project_fccback_description: 'Learning the principles of a server, using Node as javascript in the backend, learning about security and frameworks related.',

    project_fccfront_status: "Click To See the whole :)",
    project_fccfront_title: 'Some Front-End projects',
    project_fccfront_role: 'Student',
    project_fccfront_context: 'Learning UI / UX and software engineering',
    project_fccfront_description: 'By doing this projects, I followed user stories, had to use algorithms in order to create what I was asked to.',

  },
};
