export default {
  locale: 'en',
  messages: {
    siteTitle: 'Valentin Portillo Portfolio',
    addPost: 'Add Post',
    switchLanguage: 'Switch Language',
    twitterMessage: 'We are on Twitter',
    by: 'By',
    deletePost: 'Delete Post',
    createNewPost: 'Create new post',
    authorName: 'Author\'s Name',
    postTitle: 'Post Title',
    postContent: 'Post Content',
    submit: 'Submit',
    comment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	}`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
    	  =0 {does not have <i style='font-style: italic'>any</i> comments}
    	  =1 {has <i style='font-style: italic'>#</i> comment}
    	  other {has <i style='font-style: italic'>#</i> comments}
    	}`,
    nestedDateComment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
      } as of {date}`,
    profileTitle: 'Profile',
    menuAbout: 'Main',
    menuSkills: 'Skills',
    menuResume: 'Resume',
    menuContact: 'Contact',
    Me1:'I\'m a Universidad Nacional Autónoma de México (UNAM) Graduate, right now looking for a master.',
    Me2: 'I\'ve worked in Project Management, Business Analysis and Software Developement. Being Software Development my favorite and mainly working in back-end Developement.',
    Me3: 'Always interested in Computer Science deepening knowledge and challenges.',
    KeyW: 'Key Words',
    //Soft Skills
    SS1: 'Analytic',
    SS2: 'Commitment',
    SS3: 'Problem Solver',
    SS4: 'Learner',
    SS5: 'Team-Work',
    SS6: 'Add Value',
    ss11: 'Understand the requirements',
    ss12: 'Develop according to needs',
    ss21: 'Deliver Ended Products',
    ss31: 'Find the root',
    ss32: 'Develop a logical step-by-step',
    ss33: 'Deliver a system',
    ss41: 'Self-taught',
    ss42: 'Enthousiastic',
    ss43: 'Versatile',
    ss51: 'Know How',
    ss52: 'Social',
    ss53: 'Ask & Answer',
    ss61: 'Proposals',
    ss62: 'Business / ethical directed reasoning',
    //hardSkills
    ttLang: 'Languages',
    ttProgLang: 'Programming Languages',
    ttStacks: 'Stacks',
    ttFrameworks: 'Frameworks',
    ttOther: 'Other',
    //Resume
    ResHighShool: ' Lycée Franco Mexicain (High School)',
    ResHighShoolSpe: 'Engineering Science Specialization',
    ResUniv: 'Universidad Nacional Autónoma de México - UNAM',
    ResUnivSpe: 'Bachelor of Science in Civil Engineering',
    ResDiploIMEI: 'Intelligent Building Mexican Institute - IMEI',
    ResDiploIMEISpe: 'Speciality - Intelligent & Sustainable Buildings Technology',
    ResStudClubCICM: 'CICM Students Club Memeber',
    ResStageIUNAM: 'Traineeship at a InnovaUNAM (business incubator)',
    ResSolarDec: 'Solar Decathlon Europe 2014',
    ResSolarDecRole: 'Leader, Civil Engineering Responsible',
    ResSolarDecPrices: 'Won 3 prices (1° Engineering, 2° Urbanism, 3° Sustainability)',
    ResThesis: 'Author and Expositor of an article regarding my bachelor thesis (\'Analysis, Design and Construction of the CASA TEAM project\')',
    ResICAF: 'ICA FLUOR',
    ResICAFRole: 'Project Engineer',
    ResICAFDesc: 'Program follow up, alerts, recovery plan, management level reports, forecasts, productivity.',
    ResICAFAchi: 'Follow Up Automation',
    ResJacEng: 'Jacobs Engineering',
    ResJacEngRole: 'Project Scheduler',
    ResJacEngDesc: 'Interactive planning, Master Plan and WBS creation, program follow up, alerts, forecasts, productivity, recovery plan, management level reports, and resources graph.',
    ResJacEngAchi: 'Follow Up Automation',
    ResCitiB: 'Citi Banamex',
    ResCitiBRole: 'Project Manager Jr. / IT Business Analyst',
    ResCitiBDesc: 'Intermediary between business, software developers and specialists. IT BA SDLC deliverables. Data Qty & Project Controls RPA, data analysis and visualization. Requirements and solutions analysis.',
    ResCitiBAchi: 'Follow Up Automation',
    ResDiploTUDelft: 'TUDelft - TPM1x: Creative Problem Solving and Decision Making',
    ResDiploHarv: 'Harvard - CS50: Introduction to Computer Science',
    ResDiploFCCFront: 'FreeCodeCamp - Front End Certification',
    ResDiploSAOpSys: 'Saylor Academy - CS401: Operating Systems',
    ResMutuo: 'Mutuo Financiera',
    ResMutuoRole: 'Software Developer',
    ResMutuoDesc: 'Internal software development (MVC) and API, RPA for different projects (get/analyze and deduce from data) using Laravel framework mainly and VBA.',
    ResMutuoAchi: 'Projects Follow Up Automation, Scalability, Financial Projects',
    ResDiploSAIntroDB: 'Saylor Academy - CS403: Introduction to Modern Databases',
    ResDiploSAAlgorithm: 'Saylor Academy - CS303: Algorithms',
    //Form
    Name: 'Name',
    Send: 'Send',
    Email: 'Email',
    Industry: 'Industry',
    Purpose: 'Purpose',
  
    WriteToMe: 'Write to me :)',

    //Time
    January: 'January',
    February: 'February',
    March: 'March',
    June: 'June',
    September: 'September',
    October: 'October',
    December: 'December',
    ToDate: 'To Date',
  },
};
