export default {
  locale: 'fr',
  messages: {
    siteTitle: 'MERN blog de démarrage',
    addPost: 'Ajouter Poster',
    switchLanguage: 'Changer la Langue',
    twitterMessage: 'Nous sommes sur Twitter',
    by: 'Par',
    deletePost: 'Supprimer le message',
    createNewPost: 'Créer un nouveau message',
    authorName: 'Nom de l\'auteur',
    postTitle: 'Titre de l\'article',
    postContent: 'Contenu après',
    submit: 'Soumettre',
    comment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	} (in real app this would be translated to French)`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
    	  =0 {does not have <i style='font-style: italic'>any</i> comments}
    	  =1 {has <i style='font-style: italic'>#</i> comment}
    	  other {has <i style='font-style: italic'>#</i> comments}
    	} (in real app this would be translated to French)`,
    nestedDateComment: `user {name} {value, plural,
  		  =0 {does not have any comments}
  		  =1 {has # comment}
  		  other {has # comments}
      } as of {date} (in real app this would be translated to French)`,
      profileTitle: 'Profil',
      menuAbout: 'À propos',
      menuSkills: 'Compétences',
      menuResume: 'Résumé',
      menuContact: 'Contacter',
      menuProjects: 'Projets',
      clickable_logos: 'Les logos sont cliquables',
      Me1: 'Hello! :)',
      Me2: 'J\'ai développé du logiciel pour des besoins d\'entreprise et fait de l\'analyse de données depuis le début de ma carrière. Au début de ma carrière, j\'ai fait de l\'ETL, et de la modélisation pour prédire le comportement des projets et créer un tableau de bord pour la prise de décision comme outil pour les managers. Ce logiciel, celui que j\'ai créé à cette fin a été utilisé dans de multiples projets d\'ingénierie et de construction. C\'est ainsi que j\'ai été captivé par le pouvoir des logiciels et de la prise de décision.'
        + 'J\'ai donc voulu en apprendre davantage et plonger dans ces sujets. Je jouais déjà avec les données, mais je sentais que je devais améliorer au sujet du sotware et dans les compétences en matière de données. Comme prochaine étape, j\'ai décidé de commencer par me plonger dans l\'informatique puisque c\'est la base. Et puis, il était temps pour les données, alors j\'ai fait un master en science des données qui est intéressant et époustouflant.',
      Me3: 'Actuellement, en raison d\'opportunités intéressantes qui se sont présentées, j\'occupe un poste d\'ingénieur logiciel (j\'adore ça) mais je suis également ouvert à un poste en science des données pour pouvoir mettre en pratique mes connaissances (un poste hybride serait génial). Les choses que j\'aime ou qui me stimulent le plus sont : '
        + 'trouver des solutions algorithmiques (algorithmes, théorie des graphes, recherche opérationnelle), aider à la prise de décision (data engineering, feateures engineering, modélisation, visualisation des données), améliorer le code (propre, performant et malin), créer des fonctionnalités de bout en bout, proposer des systèmes (ou des solutions) et ajouter de la valeur au client. Et bien sûr, apprendre et découvrir. '
        + 'Un sujet que je trouve intéressante c\'est NLP',
      Me4: `Comme vous pouvez noter plus en bas, je connais plusieurs langages professionnellement, VBA pour deux ans (analyse de données et ETL), PHP (Laravel) pour plus d'un an (FullStaclk, ETL, analyse de données), Javascript (FullStack) et Python (Science des données) pour deux ans. Dans mes projets personnels, le stack Javascript domine. Dans des projets de recherche et académiques, majoritairement c'est Python.
        Pour des bases de données, j'utilise indifféremment MongoDB et MySQL en accord au projet. J'ajoute que les métiers où j'ai appliqué le développement ce sont en gestion, finances, recherche et l'immobilier.`
        + `Grâce à ces faits et à l'exprérience, je me considère en étant agnosique du language et du framework.`,
      MeConc: 'Finalement, si vous êtes arrivés à cette partie de ma petite introduction, n\'hésitez pas à me contacter et me demander au sujet de mes projets et parcours. Il y a un link au final. Je vous invite à regarder mes projets, mon "résumé roulant" et si vous n\'êtes pas encore motivé à me contacter (à la fin, le mail et mon linkedin se trouvent), vous pouvez me donner un feedback. De toute façon, merci et bon recrutement ! :)',
      KeyW: 'Mots Clés',
      KeyWords: 'Software Engineering, Data Science, Computer Science, Artificial Intelligence, Automation, Business Analysis, Project Management, Operational Research, Entrepreneurship',
      //Soft Skills
      SS1: 'Analytique',
      SS2: 'Engagé',
      SS3: 'Résolveur de problèmes',
      SS4: 'Apprenant',
      SS5: 'Travail en équipe',
      SS6: 'Ajouter de la valeur',
      SS7: '"Hands On"',
      ss11: '& Curieux',
      ss12: 'Logique, Raisonnement, Approfondir',
      ss21: 'Délivrer des produits finis',
      ss31: 'Trouver la cause',
      ss32: 'Développer un processus logique',
      ss33: 'Délivrer un système',
      ss41: 'Autodidacte',
      ss42: 'Enthousiaste',
      ss43: 'Poser des questions',
      ss51: 'Savoir faire',
      ss52: 'Social',
      ss53: 'Demander & Répondre',
      ss61: 'Propositions',
      ss62: 'Compréhension du Business/Produit',
      ss71: 'Essayer des nouvelles choses',
      ss72: 'Entthousiaste à créer',
      //hardSkills
      ttLang: 'Langues',
      ttProgLang: 'Langues de programmation',
      ttStacks: 'Stacks',
      ttFrameworks: 'Frameworks/Librairies',
      ttOther: 'Autres',
      ttGraphTheoryLibraries: 'Bibliothèques de Théorie de Graphes',
      ttBackendLibraries: 'Bibliothèques de Backend',
      ttDataScienceLibraries: 'Bibliothèques de Data Science',

      //Resume
      ResHighShool: ' Lycée Franco Mexicain',
      ResHighShoolSpe: 'Spécialité  Sciences de l\'ingénieur',
      ResUniv: 'Universidad Nacional Autónoma de México - UNAM',
      ResUnivSpe: 'Licence en Sciences Génie Civil',
      ResDiploIMEI: 'Institut Mexicain du Bâtiment Intelligent - IMEI',
      ResDiploIMEISpe: 'Spécialité - Technologie des Bâtiments Intelligents et Durables',
      ResStudClubCICM: 'CICM Membre du club d\'étudiants',
      ResStageIUNAM: 'Stage en InnovaUNAM (incubateur d\'entreprises)',
      ResSolarDec: 'Solar Decathlon Europe 2014',
      ResSolarDecRole: 'Leader, Responsable Génie Civil',
      ResSolarDecPrices: 'Gagné 3 prix (1° Ingénierie, 2° Urbanisme, 3° Durabilité)',
      ResThesis: 'Auteur et Expositeur de l\'article concernant ma thèse (Analyse, Conception et Construction du projet CASA UNAM)',
      ResICAF: 'ICA FLUOR',
      ResICAFRole: 'Ingénieur de Projet',
      ResICAFDesc: 'Suivi du programme, alertes, plan de récupération, prévisions, productivité, rapports niveau gestion.',
      ResICAFAchi: 'Automatisation du suivi du programme',
      ResJacEng: 'Jacobs Engineering',
      ResJacEngRole: 'Planificateur de Projet',
      ResJacEngDesc: 'Planification interactive, plan directeur, création du WBS, suivi du programme, alertes, prévisions, productivité. Plan de récupération, rapports niveau gestion.',
      ResJacEngAchi: 'Automatisation du suivi du programme',
      ResCitiB: 'Citi Banamex',
      ResCitiBRole: 'Chef de projet Junior. / IT Business Analyst',
      ResCitiBDesc: 'Intermédiaire entre la partie commerciale/d\'affaires, développeurs de logiciel, et spécialistes. IT BA SDLC livrables, qualité des données et contrôle de projet RPA, analyse des données et visualisation. Analyse des exigences et des solutions. Méthode : SDLC.',
      ResCitiBAchi: 'Automatisation du suivi du programme',
      ResDiploTUDelft: 'TUDelft - TPM1x: Creative Problem Solving and Decision Making',
      ResDiploHarv: 'Harvard - CS50: Introduction to Computer Science',
      ResDiploFCCFront: 'FreeCodeCamp - Front End Certification',
      ResDiploSAOpSys: 'Saylor Academy - CS401: Operating Systems',
      ResMutuo: 'Mutuo Financiera',
      ResMutuoRole: 'Software Engineer',
      ResMutuoDesc: 'Développement du software interne, BPA & RPA pour des différents projets (obtenir/analyser et déduire des données). Méthode : Agile.',
      ResMutuoAchi: 'Automatisation du suivi des projets, évolutivité, projets financiers',
      ResDiploSAIntroDB: 'Saylor Academy - CS403: Introduction to Modern Databases',
      ResDiploSAAlgorithm: 'Saylor Academy - CS303: Algorithms',
      ResIMT: 'Institut Mines Télécom - IMT',
      ResIMTP: 'Projet IMT',
      ResIMTSpe: 'Master of Science en Sciences des Données',
      ResIMTCours: 'Intelligence Artificielle, Langages et Logique, Graphes, Génie Logiciel, Mathématiques { Proba, Stat, Alg }, Traitement des signaux, Recherche Opérationnelle, Big Data, Data Mining',
      ResIMTP1: 'Projet: Algorithme génétique pour l\'optimisation d\'un réseau de chauffage',
      ResIMTP2: 'Projet: Détection Navire en utilisant imagerie satellite, IA et Statistiques',
      ResIMTP3: 'Projet: Compilateur type Expr - Pfx (Lexer, Parser, NLP, Programmation Fonctionelle)',
      ResIMTP4: 'Projet: Simulation Infection et traitement réseaux sociaux (Graphes)',
      ResIMTP5: 'Projet: Recommandation de profils à des postes de travail (RH)',
      ResIRH: 'Plataforme de Location Habitation',
      ResIRHRole: 'Projet Personnel',
      ResIRHDesc: 'Déveloper une Application Web pour gèrer la location habitation',
      ResIMTRole: 'Stagiaire Data Science',
      ResIMTDesc: 'Classification non supervisée de caractéristiques obtenues de signaux ECG pour trouver des groupes indiquant battements de cœur',
      ResIMTCHLG: 'Challenge IMT Disrupt’ Campus 2019',
      ResIMTCHLGRole: 'Participant',
      ResIMTCHLGDesc: 'Évenement de 4 jours dédiés à l\'Intelligence Artificielle avec des conférences, activités, rencontres avec des entreprises et un étude de cas. Pour moi, l\'étude de cas était pour BNP, pour leur nouvel "centre d\'innovation" BivWak. C\'était une manière de identification en utilisant l\'IA.',
      ResAMA: 'Amadeus',
      ResAMARole: 'Data Science Intern',
      ResAMADesc: 'Détection de Fraude. Recherche et implémentation MVP. Proposed two sources feeding data with features engineering and a pipeline of models.',
      ResSMOOD: 'Smood',
      ResSMOODRole: 'Full Stack engineer',
      ResSMOODDesc: 'Améliorer les différents produits concernant les associés (restaurants). Implémenter des "features", developperdes solutions pour des "business cases".',
      ResND: 'Gerer le process d\'interior design',
      ResNDRole: 'Projet Personnel',
      ResNDDesc: 'Une application web pour faciliter la gestion de budgets et la relation client.',
      ResKNAP: 'Knap',
      ResKNAPRole: 'Full Stack engineer',
      ResKNAPDesc: 'Création de features, solutions pour l\'app client, fraude et de gestion du produit.',

      //Form
      Name: 'Prénom',
      Send: 'Envoyer',
      Email: 'Courrier électronique',
      Industry: 'Industrie',
      Purpose: 'Objectif',
      WriteToMe: 'Écris-moi :)',
      SentMessage: 'Message envoyé!! :). Merci de me contacter, je me mettrai en contact avec vous. Bonne journée!',
      MessageSentFail: 'Message PAS envoyé :(, essayez de nouveau plus tard s-v-p, ou contactez moi directement à mon courrier électronique: valentin.pg@outlook.com. Merci!',
      WaitForIt: 'Wait for it ...',
      //Time
      January: 'Janvier',
      February: 'Février',
      March: 'Mars',
      June: 'Juin',
      September: 'Septembre',
      October: 'Octobre',
      December: 'Décembre',
      ToDate: 'Á aujourd\'hui',

       //Projects
       print_ph1: 'Vous trouverez listés quelques projets que j\'ai développés ou participé à développer. Soient les plus intéressants et les plus représentatifs de mon parcours.', 
    print_ph2: 'Les sujets et les contextes sont divers. Principalement des approches software engineering, fullstack developement et enfin data science. Sous des contextes tels que le management, les finances, la recherche et l\'académique.',
    print_ph3_1: 'Si vous êtes plus curieux de mes projets, je vous encourage à vous rendre à ma',
    print_ph3_2: 'page web (https://portfolio-vp.herokuapp.com)',
    print_ph3_3: 'qui est sûrement plus dynamique et plus riche en contenu.',
    print_ph3_4: 'Le démarrage peut prendre quelques secondes.',
    print_ph4: 'Bonne lecture et si vous l\'aimez, ou vous voulez simplement en parler, mettons-nous en contact',

    click_for_more: 'Clickez pour voir plus',
    project_comp_title: 'Compilateur PFX - EXPR',
    project_comp_description: 'Créer un compilateur en utilisant le cadre pfx-expr. En utilisant un lexer et un parser, le nouvel "langage de programmation" est identifié et toutes ses opérations ordonnées dans une pipe (expr) laquelle sera calculée après récursivement (pfx). Le nouveau langage utilise variables et lambda calcul.',
    project_comp_context: 'Programmation Fonctionelle, NLP, Langages et Logique',
    project_comp_status: 'Click pour voir le code',

    project_irent_description: 'Développer une plateforme web de gestion de l\'immobilier pour les entreprises traditionnelles. Fonctionnalités: Payements, création d\'utilisateurs/contrôle de rôles, gestion de finances et documentation, calendrier, contrats (comme google docs), highlights et visualisation/analyse des données.',
    project_homebudget_description: 'Développer une plataformw où les architectes d\'intérieur seront capables de communiquer avec leurs clients tout au long du projet. Gerer les différentes étapes. Faciliter la préparation du projet de la part du designer. Also faciliate their design preparation.',
    
    project_valhalla_status: 'Désolé, "Valhalla" est privé, mais vous pouvez cliquer dessus et accéder à la page publique :)',
    project_valhalla_title: 'Fintech Core Banking System (ERP)',
    project_valhalla_role: 'Software Engineer',
    project_valhalla_context: 'Fintech / RPA',
    project_valhalla_description: 'Nous voulions créer notre propre logiciel pour modeler chaque produit et produit financier. Alors, vous y trouveriez une énorme structure de base de données, clients, products, financial products, et tout ce que vous pouvez imaginer pour automatiser et aider le métier.',
  
    project_datavis_status: 'Cliquez sur les links :)',
    project_datavis_title: 'Visualisation des données',
    project_datavis_role: 'Étudiant',
    project_datavis_context: 'Visualisation des données',
    project_datavis_description: "Les données sont une des choses les plus précieuses pour le commerce et, un des outils les plus révélateurs pour la prise de décisions, alors, c'était à faire.",

    project_pm_status: "Désolé, projets privés à cause d'information sensible, mais il y a une vidéo :)",
    project_pm_title: 'Outil de Suivi de Projets',
    project_pm_role: 'Project Manager / Software Engineer',
    project_pm_context: 'Gestion du Projet / Produit / RPA',
    project_pm_description: "Pour éviter des erreurs et briller au suivi de projet, j'ai créé en ICA FLUOR, Jacobs, Citi Banamex, et Mutuo Financiera des fichiers comme celui ci pour moi comme PM ou pour le PMOffice.",
    
    project_ttt_status: "Cliquez pour jouer :)",
    project_ttt_title: 'Jeu Tic-Tac-Toe',
    project_ttt_role: 'Étudiant',
    project_ttt_context: "Principes de l'Intéligence Artificielle",
    project_ttt_description: "En étudiant les principes de l'IA, c'est un projet pour pratiquer et bien comprendre cet exemple.",

    project_cs50final_status: "Cliquez pour voir :)",
    project_cs50final_title: 'CS50 Final - Projet Final',
    project_cs50final_role: 'Étudiant',
    project_cs50final_context: 'Développement Web',
    project_cs50final_all_proj: 'Tous les projects CS50',
    project_cs50final_description: "Pour le projet final, j'ai choisi de faire un logiciel pour la gestion d'une cafétéria. Imaginer ce que une cafétéria a besoin, proposer et créer ce qui ajoute le plus de valeur possible.",
  
    project_cs50p8_status: "Cliquez pour voir :)",
    project_cs50p8_title: 'CS50 Pset8 - Google Maps & Search',
    project_cs50p8_role: 'Étudiant',
    project_cs50p8_context: 'Développement Web',
    project_cs50p8_description: 'Un projet fait pour le TP8 pendant le cours CS50.',

    project_cs50p7_status: "Cliquez pour voir :)",
    project_cs50p7_title: 'CS50 Pset7 - Stock Exchange',
    project_cs50p7_role: 'Étudiant',
    project_cs50p7_context: 'Développement Web',
    project_cs50p7_description: 'Un projet fait pour le TP7 pendant le cours CS50.',

    project_fccback_status: "Cliquez sur les links :)",
    project_fccback_title: 'Quelques projets Back-End',
    project_fccback_role: 'Étudiant',
    project_fccback_context: 'Apprenant principalement NodeJS et quelques frameworks',
    project_fccback_description: "J'ai appris les principes d'un serveur avec Node comme javascript en Back End, la sécurité et d'autres 'frameworks' liés.",

    project_fccfront_status: "Cliquez pour voir plusieurs examples :)",
    project_fccfront_title: 'Quelques projets Front-End',
    project_fccfront_role: 'Étudiant',
    project_fccfront_context: 'Apprenant UI / UX et software engineering',
    project_fccfront_description: "En faisant ces projets, j'ai dû poursuivre des histoires d'utilisateur, utiliser des algorithmes pour créer ce qu¿on me demandait.",

    project_ds_multiple_title: 'Quelques projets DS intéressants',
    project_ds_multiple_role: 'Étudiant',
    project_ds_multiple_context: 'MSc Data Science',
    project_ds_multiple_description: 'Abordé plusieurs sujets avec des outils différents et méthodologie: NLP, AI, ML, Graphes, Operational Research sont ceux les plus interessants je pense.',
  },
};
