export default {
  locale: 'fr',
  messages: {
    siteTitle: 'MERN blog de démarrage',
    addPost: 'Ajouter Poster',
    switchLanguage: 'Changer la Langue',
    twitterMessage: 'Nous sommes sur Twitter',
    by: 'Par',
    deletePost: 'Supprimer le message',
    createNewPost: 'Créer un nouveau message',
    authorName: 'Nom de l\'auteur',
    postTitle: 'Titre de l\'article',
    postContent: 'Contenu après',
    submit: 'Soumettre',
    comment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	} (in real app this would be translated to French)`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
    	  =0 {does not have <i style='font-style: italic'>any</i> comments}
    	  =1 {has <i style='font-style: italic'>#</i> comment}
    	  other {has <i style='font-style: italic'>#</i> comments}
    	} (in real app this would be translated to French)`,
    nestedDateComment: `user {name} {value, plural,
  		  =0 {does not have any comments}
  		  =1 {has # comment}
  		  other {has # comments}
      } as of {date} (in real app this would be translated to French)`,
      profileTitle: 'Profil',
      menuAbout: 'Main',
      menuSkills: 'Compétences',
      menuResume: 'Résumé',
      menuContact: 'Contacter',
      menuProjects: 'Projets',
      Me1: 'J\'ai commencé ma carrière professionnelle comme Ingénieur Civil mais j\'ai basculé vers informatique plutôt parce que j\'aime la logique et la technologie dès toujours. En tant qu\'ingénieur civil, j\'ai travaillé dans la plupart en faisant de la gestion puisque je trouve organiser et la prise de décisions très intéressantes, point curieux : j\'automatisais mon travail. Ces jours-ci, je fais un master lié à l\'informatique pour pouvoir mélanger cet intérêt  et des sujets que j\'ai toujours aimé : MSc en Science des données où les données doivent être comprises, tendances nous amènent aux décisions et encore, la visualisation est cruciale pour la communication, tout cela avec l\'aide des algorithmes et la logique.',
      Me2: 'Avant mon premier travail lié à l\'informatique, comme déjà mentionné, j\'automatisais mes activités du travail, et, en ajoutant un plan de 2 ans pour acquérir le savoir d\'un étudiant en informatique, j\'ai réussi à travailler comme un en commençant avec Automatisation et puis, comme un ingénieur logiciel principalement dans le domaine des finances et de la banque.',
      Me3: 'Alors, pour mettre en évidence, ce chemin montre, entre d\'autres choses, persévérance, autonomie et motivation. En étant ces valeurs très importantes et celles que je chercherais, entre d\'autres choses, dans des candidats que je prendrais.',
      Me4: 'Avant conclure, humilité à part, j\'ai les compétences pour faire un projet de génie logiciel début-fin, les compétences pour faire de la gestion en incluant leadership et structuration (j\'ai travaillé aussi en SCRUM, Waterfall, PMI), les compétences Data Science comme communication, analyse et logique, et la faim d\'appliquer les nouvelles connaissances acquises au MSc.',
      MeConc: 'Finalement, je vous invite à regarder mes projets, mon "résumé roulant" et si vous n\'êtes pas encore motivé à me contacter (à la fin, le mail et mon linkedin se trouvent), peut-être vous pouvez me donner une retroalimentation pour améliorer. De toute façon, merci et bon recrutement ! :)',
      KeyW: 'Mots Clés',
      KeyWords: 'Data Science, Computer Science, Artificial Intelligence, Business Analysis, Automation, Project Management, Optimization, Entrepreneurship',
      //Soft Skills
      SS1: 'Analytique',
      SS2: 'Engagé',
      SS3: 'Résolveur de problèmes',
      SS4: 'Apprenant',
      SS5: 'Travail en équipe',
      SS6: 'Ajouter de la valeur',
      SS7: '"Hands On"',
      ss11: '& Curieux',
      ss12: 'Logique, Raisonnement, Approfondir',
      ss21: 'Délivrer des produits finis',
      ss31: 'Trouver la cause',
      ss32: 'Développer un processus logique',
      ss33: 'Délivrer un système',
      ss41: 'Autodidacte',
      ss42: 'Enthousiaste',
      ss43: 'Poser des questions',
      ss51: 'Savoir faire',
      ss52: 'Social',
      ss53: 'Demander & Répondre',
      ss61: 'Propositions',
      ss62: 'Compréhension du Business/Produit',
      ss71: 'Essayer des nouvelles choses',
      ss72: 'Entthousiaste à créer',
      //hardSkills
      ttLang: 'Langues',
      ttProgLang: 'Langues de programmation',
      ttStacks: 'Stacks',
      ttFrameworks: 'Frameworks/Librairies',
      ttOther: 'Autres',
      //Resume
      ResHighShool: ' Lycée Franco Mexicain',
      ResHighShoolSpe: 'Spécialité  Sciences de l\'ingénieur',
      ResUniv: 'Universidad Nacional Autónoma de México - UNAM',
      ResUnivSpe: 'Licence en Sciences Génie Civil',
      ResDiploIMEI: 'Institut Mexicain du Bâtiment Intelligent - IMEI',
      ResDiploIMEISpe: 'Spécialité - Technologie des Bâtiments Intelligents et Durables',
      ResStudClubCICM: 'CICM Membre du club d\'étudiants',
      ResStageIUNAM: 'Stage en InnovaUNAM (incubateur d\'entreprises)',
      ResSolarDec: 'Solar Decathlon Europe 2014',
      ResSolarDecRole: 'Leader, Responsable Génie Civil',
      ResSolarDecPrices: 'Gagné 3 prix (1° Ingénierie, 2° Urbanisme, 3° Durabilité)',
      ResThesis: 'Auteur et Expositeur de l\'article concernant ma thèse (Analyse, Conception et Construction du projet CASA UNAM)',
      ResICAF: 'ICA FLUOR',
      ResICAFRole: 'Ingénieur de Projet',
      ResICAFDesc: 'Suivi du programme, alertes, plan de récupération, prévisions, productivité, rapports niveau gestion.',
      ResICAFAchi: 'Automatisation du suivi du programme',
      ResJacEng: 'Jacobs Engineering',
      ResJacEngRole: 'Planificateur de Projet',
      ResJacEngDesc: 'Planification interactive, plan directeur, création du WBS, suivi du programme, alertes, prévisions, productivité. Plan de récupération, rapports niveau gestion.',
      ResJacEngAchi: 'Automatisation du suivi du programme',
      ResCitiB: 'Citi Banamex',
      ResCitiBRole: 'Chef de projet Junior. / IT Business Analyst',
      ResCitiBDesc: 'Intermédiaire entre la partie commerciale/d\'affaires, développeurs de logiciel, et spécialistes. IT BA SDLC livrables, qualité des données et contrôle de projet RPA, analyse des données et visualisation. Analyse des exigences et des solutions. Méthode : SDLC.',
      ResCitiBAchi: 'Automatisation du suivi du programme',
      ResDiploTUDelft: 'TUDelft - TPM1x: Creative Problem Solving and Decision Making',
      ResDiploHarv: 'Harvard - CS50: Introduction to Computer Science',
      ResDiploFCCFront: 'FreeCodeCamp - Front End Certification',
      ResDiploSAOpSys: 'Saylor Academy - CS401: Operating Systems',
      ResMutuo: 'Mutuo Financiera',
      ResMutuoRole: 'Software Engineer',
      ResMutuoDesc: 'Développement du software interne, BPA & RPA pour des différents projets (obtenir/analyser et déduire des données). Méthode : Agile.',
      ResMutuoAchi: 'Automatisation du suivi des projets, évolutivité, projets financiers',
      ResDiploSAIntroDB: 'Saylor Academy - CS403: Introduction to Modern Databases',
      ResDiploSAAlgorithm: 'Saylor Academy - CS303: Algorithms',
      ResIMT: 'Institut Mines Télécom - IMT',
      ResIMTP: 'Projet IMT',
      ResIMTSpe: 'Master of Science en Sciences des Données',
      ResIMTCours: 'Intelligence Artificielle, Langages et Logique, Graphes, Génie Logiciel, Mathématiques { Proba, Stat, Alg }, Traitement des signaux, Recherche Opérationnelle, Big Data, Data Mining',
      ResIMTP1: 'Projet: Algorithme génétique pour l\'optimisation d\'un réseau de chauffage',
      ResIMTP2: 'Projet: Détection Navire en utilisant imagerie satellite, IA et Statistiques',
      ResIMTP3: 'Projet: Compilateur type Expr - Pfx (Lexer, Parser, NLP, Programmation Fonctionelle)',
      ResIMTP4: 'Projet: Simulation Infection et traitement réseaux sociaux (Graphes)',
      ResIRH: 'Plataforme de Location Habitation',
      ResIRHRole: 'Projet Personel',
      ResIRHDesc: 'Déveloper une Application Web pour gèrer la location habitation',
      ResIMTRole: 'Stagiaire Data Science',
      ResIMTDesc: 'Classification non supervisée de caractéristiques obtenues de signaux ECG pour trouver des groupes indiquant battements de cœur',
      ResIMTCHLG: 'Challenge IMT Disrupt’ Campus 2019',
      ResIMTCHLGRole: 'Participant',
      ResIMTCHLGDesc: 'Évenement de 4 jours dédiés à l\'Intelligence Artificielle avec des conférences, activités, rencontres avec des entreprises et un étude de cas. Pour moi, l\'étude de cas était pour BNP, pour leur nouvel "centre d\'innovation" BivWak. C\'était une manière de identification en utilisant l\'IA.',
      //Form
      Name: 'Prénom',
      Send: 'Envoyer',
      Email: 'Courrier électronique',
      Industry: 'Industrie',
      Purpose: 'Objectif',
      WriteToMe: 'Écris-moi :)',
      SentMessage: 'Message envoyé!! :). Merci de me contacter, je me mettrai en contact avec vous. Bonne journée!',
      MessageSentFail: 'Message PAS envoyé :(, essayez de nouveau plus tard s-v-p, ou contactez moi directement à mon courrier électronique: valentin.pg@outlook.com. Merci!',
      WaitForIt: 'Wait for it ...',
      //Time
      January: 'Janvier',
      February: 'Février',
      March: 'Mars',
      June: 'Juin',
      September: 'Septembre',
      October: 'Octobre',
      December: 'Décembre',
      ToDate: 'Á aujourd\'hui',

       //Projects

    project_comp_title: 'Compilateur PFX - EXPR',
    project_comp_description: 'Créer un compilateur en utilisant le cadre pfx-expr. En utilisant un lexer et un parser, le nouvel "langage de programmation" est identifié et toutes ses opérations ordonnées dans une pipe (expr) laquelle sera calculée après récursivement (pfx). Le nouveau langage utilise variables et lambda calcul.',
    project_comp_context: 'Programmation Fonctionelle, NLP, Langages et Logique',
    project_comp_status: 'Click pour voir le code',

    project_irent_description: 'Développer une plateforme web pour la gestion de la location habitation pour les entreprises traditionneles (en pensant plutôt en un administrateur immobilier pour qu\'elles puissent controler les proprietés qu\'elles gèrent. Dés la communication, raports, contrats, jusqu\'à paiements et visualisation et analyse des données.',
    
    project_valhalla_status: 'Désolé, "Valhalla" est privé, mais vous pouvez cliquer dessus et accéder à la page publique :)',
    project_valhalla_title: 'Fintech Core Banking System (ERP)',
    project_valhalla_role: 'Software Engineer',
    project_valhalla_context: 'Fintech / RPA',
    project_valhalla_description: 'Nous voulions créer notre propre logiciel pour modeler chaque produit et produit financier. Alors, vous y trouveriez une énorme structure de base de données, clients, products, financial products, et tout ce que vous pouvez imaginer pour automatiser et aider le business ...',
  
    project_datavis_status: 'Cliquez sur les links :)',
    project_datavis_title: 'Visualisasion des données',
    project_datavis_role: 'Étudiant',
    project_datavis_context: 'Visualisasion des données',
    project_datavis_description: "Les données sont une des choses les plus précieuses pour le commerce et, une des outils les plus révélateurs pour la prise de décisions, alors, c'était à faire.",

    project_pm_status: "Désolé, projets privés à cause d'information sensible, mais il y a une vidéo :)",
    project_pm_title: 'Outil de Suivi de Projets',
    project_pm_role: 'Project Manager / Software Engineer',
    project_pm_context: 'Gestion du Projet / Produit / RPA',
    project_pm_description: "Pour éviter des erreurs et briller au suivi de projet, j'ai créé en ICA FLUOR, Jacobs, Citi Banamex, et Mutuo Financiera des fichiers comme celui ci pour moi comme PM ou pour le PMOffice.",
    
    project_ttt_status: "Cliquez pour jouer :)",
    project_ttt_title: 'Jeu Tic-Tac-Toe',
    project_ttt_role: 'Étudiant',
    project_ttt_context: "Principes de l'Intéligence Artificielle",
    project_ttt_description: "En étudiant les principes de l'IA, c'est un projet pour pratiquer et bien comprendre cet exemple.",

    project_cs50final_status: "Cliquez pour voir :)",
    project_cs50final_title: 'CS50 Final - Projet Final',
    project_cs50final_role: 'Étudiant',
    project_cs50final_context: 'Développement Web',
    project_cs50final_description: "Pour le projet final, j'ai choisi de faire un logiciel pour la gestion d'une cafétéria. Si vous voulez comprendre son fonctionnement, regardez la vidéo ou cliquez sur le titre.",
  
    project_cs50p8_status: "Cliquez pour voir :)",
    project_cs50p8_title: 'CS50 Pset8 - Google Maps & Search',
    project_cs50p8_role: 'Étudiant',
    project_cs50p8_context: 'Développement Web',
    project_cs50p8_description: 'Un projet fait pour le TP8 pendant le cours CS50.',

    project_cs50p7_status: "Cliquez pour voir :)",
    project_cs50p7_title: 'CS50 Pset7 - Stock Exchange',
    project_cs50p7_role: 'Étudiant',
    project_cs50p7_context: 'Développement Web',
    project_cs50p7_description: 'Un projet fait pour le TP7 pendant le cours CS50.',

    project_fccback_status: "Cliquez sur les links :)",
    project_fccback_title: 'Quelques projets Back-End',
    project_fccback_role: 'Étudiant',
    project_fccback_context: 'Apprenant principalement NodeJS et quelques frameworks',
    project_fccback_description: "J'ai appris les principes d'un serveur avec Node comme javascript en Back End, la sécurité et d'autres 'frameworks' liés.",

    project_fccfront_status: "Cliquez pour voir plusieurs examples :)",
    project_fccfront_title: 'Quelques projets Front-End',
    project_fccfront_role: 'Étudiant',
    project_fccfront_context: 'Apprenant UI / UX et software engineering',
    project_fccfront_description: "En faisant ces projets, j'ai dû poursuivre des histoires d'utilisateur, utiliser des algorithmes pour créer ce qu¿on me demandait.",
  },
};
